// Fill out your copyright notice in the Description page of Project Settings.


#include "KGCharacterAttributeSet.h"

#define DEBUG_ATTRIBUTE_CURRENTBVALUE_STRING(Message, x)\
 Message += FString::Printf(TEXT("%s : %f\n"),TEXT(#x), x.GetCurrentValue())


UKGCharacterAttributeSet::UKGCharacterAttributeSet()
{
}

void UKGCharacterAttributeSet::GetDebugInfoString(FString& meesage) const
{
	DEBUG_ATTRIBUTE_CURRENTBVALUE_STRING(meesage,HP);
	DEBUG_ATTRIBUTE_CURRENTBVALUE_STRING(meesage,HPMax);
	DEBUG_ATTRIBUTE_CURRENTBVALUE_STRING(meesage,HPRecovery);
	DEBUG_ATTRIBUTE_CURRENTBVALUE_STRING(meesage,MP);
	DEBUG_ATTRIBUTE_CURRENTBVALUE_STRING(meesage,MPMax);
	DEBUG_ATTRIBUTE_CURRENTBVALUE_STRING(meesage,MPRecovery);
	DEBUG_ATTRIBUTE_CURRENTBVALUE_STRING(meesage,SP);
	DEBUG_ATTRIBUTE_CURRENTBVALUE_STRING(meesage,SPMax);
	DEBUG_ATTRIBUTE_CURRENTBVALUE_STRING(meesage,SPRecovery);
	DEBUG_ATTRIBUTE_CURRENTBVALUE_STRING(meesage,Attack);
	DEBUG_ATTRIBUTE_CURRENTBVALUE_STRING(meesage,AttackSpeed);
	DEBUG_ATTRIBUTE_CURRENTBVALUE_STRING(meesage,Defence);
	DEBUG_ATTRIBUTE_CURRENTBVALUE_STRING(meesage,Exp);
	DEBUG_ATTRIBUTE_CURRENTBVALUE_STRING(meesage,Level);
	DEBUG_ATTRIBUTE_CURRENTBVALUE_STRING(meesage,Gold);

}
